### ISSUE TITLE
Open link in different editor group

### ISSUE THREAD

**Issue by ZBiener** [houkanshan/vscode-markdown-footnote#3]
This is just a question. Is there any vscode setting or a simple modification to this code that, upon clicking on a footnote link, will open the file (again) in a different editor (like the split right command) and just to the e content in the second editor? Thanks.

**Comment by houkanshan** [comment]
Sorry I missed this issue because there's something wrong with my GitHub notification setting. 
No currently you can't do this. 
But for VSCode there's feature called [peek](https://code.visualstudio.com/docs/editor/editingevolved#_peek) that allows you to open a small peek window below the current line. This is not supported by this plugin yet, but I have a plan to rewrite the code and implement this.

**Comment by ZBiener** [comment]
Thanks!
